CC=clang++
CXX_FLAGS=-Wall -Werror -Wpedantic -Wextra
DEST_DIR=./build
CXX_STD=c++14
SRC_DIR=./src
TEST_DIR=./test

APP_NAME=analyser

SRC_OBJS=

INCLUDE_PATHS=
LIBRARIES=
LIBRARY_PATHS=

clean:
	rm -r $(DEST_DIR)

env:
	mkdir -p $(DEST_DIR)

test:

app: env
